### ISSUE TITLE
executables can't be start because +x missing

### ISSUE THREAD

**Issue by b2un0** [m33ts4k0z/silabs-multipan-docker#1]
thanks for your work!

I tried to simplify your container and created a simple, pullable multiarch docker image.

but your container can't start because all executable files from your `rootfs` folder are not executable so the s6-overlay fails

https://github.com/b2un0/silabs-multipan-docker
https://github.com/b2un0/silabs-multipan-docker/pkgs/container/silabs-multipan-docker

can you help?

**Comment by m33ts4k0z** [comment]
Hello.

What if you edit the Dockerfile and add the chmod +x command there for these executables?

example, after the `COPY rootfs /`:

```RUN chmod +x /rootfs/etc/s6-overlay/s6-rc.d/zigbeed/run```

**Comment by b2un0** [comment]
fixed it with

```bash
find ./rootfs/ -type f -exec grep -rl '/bash' {} \; -exec chmod +x {} \;

find ./rootfs/ -type f -exec grep -rl '/bash' {} \; -exec git update-index --chmod=+x {} \;
````
